# render.yaml
services:
  - type: web
    runtime: go
    name: expenseTracker
    region: frankfurt
    plan: free
    branch: main

    buildCommand: |
      go mod tidy
      go build -v -o server .

    startCommand: ./server

    envVars:
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASS
        sync: false
